name: Prison
author: Primus
description: "Prison, huraaaaay :D"
version: 1.1.0
api: [3.5.1]
main: prison\Prison
depend: PurePerms
softdepend: [EconomyAPI, MassiveEconomy, PocketMoney, GoldStd]
loadbefore: [EconomyAPI, MassiveEconomy, PocketMoney, GoldStd]
load: POSTWORLD

permissions:
 prison.*:
  default: false
  description: "Allows all Prison features"
  children:
   prison.rankup:
    description: "Allows player to rankup"
    default: true
